### PR TITLE
Docker

### PR DESCRIPTION
**Pull request by burtonjc**
connected to waffleio/waffle.io-app#747

### CODE REVIEW

**Comment by homeyer** [comment]
I'm guessing you upgrading poxa at the same time?

**Comment by burtonjc** [comment]
Not sure what the deal is with the debian flag, but it has to be set...nothing to see.

**Comment by homeyer** [comment]
:+1: 

Are you going to submit a PR to poxa too?

**Comment by burtonjc** [comment]
I would like to submit a PR to them also. what do you think @homeyer?

**Pull request merged**
